import board

ANALOG_SENSORS_ENABLE_PIN = board.IO0
PH_ADC_PIN = board.A4
DO_ADC_PIN = board.A5
ONEWIRE_BUS_PIN = board.IO8

ULP_GPIO_PINS = [ANALOG_SENSORS_ENABLE_PIN, ONEWIRE_BUS_PIN]

ULP_ADC_PINS = [PH_ADC_PIN, DO_ADC_PIN]
